In [1]:
cd ..

/home/scott/Documents/git/bite-me


In [2]:
import sklearn
import pandas as pd
import numpy as np
import datetime

In [3]:
from IPython.display import HTML
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3agg.py:18: UserWarning: The Gtk3Agg backend is known to not work on Python 3.x with pycairo. Try installing cairocffi.
  "The Gtk3Agg backend is known to not work on Python 3.x with pycairo. "


In [4]:
import sklearn.linear_model
import sklearn.cross_validation

In [5]:
from eat_it import StratifiedPercentileKFold

In [6]:
from eat_it import boxcoxscaler

In [7]:
import imp

In [8]:
imp.reload(StratifiedPercentileKFold)

<module 'eat_it.StratifiedPercentileKFold' from '/home/scott/Documents/git/bite-me/eat_it/StratifiedPercentileKFold.py'>

In [9]:
rng = sklearn.utils.check_random_state(0)

In [10]:
imp.reload(StratifiedPercentileKFold)
X = np.array([[11, 12], [13, 14], [11, 12], [13, 14]])
y = np.array([0.1, 0.4, 0.8, 0.2])
cv = StratifiedPercentileKFold.StratifiedPercentileKFold(y, n_folds=2, random_state=0)
for train_index, test_index in cv:
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(X_test, y_test)

TRAIN: [2 3] TEST: [0 1]
[[11 12]
 [13 14]] [ 0.1  0.4]
TRAIN: [0 1] TEST: [2 3]
[[11 12]
 [13 14]] [ 0.8  0.2]


In [11]:
imp.reload(StratifiedPercentileKFold)
X = np.array([[11, 12], [13, 14], [11, 12], [13, 14], [11, 14]])
y = np.array([0.1, 0.4, 0.8, 0.2, 0.3])
cv = StratifiedPercentileKFold.StratifiedPercentileKFold(y, n_folds=2, random_state=0)
for train_index, test_index in cv:
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(X_test, y_test)

TRAIN: [2 3 4] TEST: [0 1]
[[11 12]
 [13 14]] [ 0.1  0.4]
TRAIN: [0 1] TEST: [2 3 4]
[[11 12]
 [13 14]
 [11 14]] [ 0.8  0.2  0.3]


In [12]:
train = pd.read_csv('data/train.csv', encoding="utf-8")

In [13]:
train

Id   Open Date            City  City Group Type  P1   P2   P3   P4  P5  \
0      0  07/17/1999        İstanbul  Big Cities   IL   4  5.0  4.0  4.0   2   
1      1  02/14/2008          Ankara  Big Cities   FC   4  5.0  4.0  4.0   1   
2      2  03/09/2013      Diyarbakır       Other   IL   2  4.0  2.0  5.0   2   
3      3  02/02/2012           Tokat       Other   IL   6  4.5  6.0  6.0   4   
4      4  05/09/2009       Gaziantep       Other   IL   3  4.0  3.0  4.0   2   
5      5  02/12/2010          Ankara  Big Cities   FC   6  6.0  4.5  7.5   8   
6      6  10/11/2010        İstanbul  Big Cities   IL   2  3.0  4.0  4.0   1   
7      7  06/21/2011        İstanbul  Big Cities   IL   4  5.0  4.0  5.0   2   
8      8  08/28/2010  Afyonkarahisar       Other   IL   1  1.0  4.0  4.0   1   
9      9  11/16/2011          Edirne       Other   IL   6  4.5  6.0  7.5   6   
10    10  08/09/2013         Kocaeli       Other   FC   9  6.0  6.0  6.0   4   
11    11  05/22/2012        İstanbul  Big Cities   IL   2  4.0  4.0  4.0   2   
12    12  02/28/2013          Ankara  Big Cities   IL   2  2.0  4.0  4.0   2   
13    13  10/16/2010        İstanbul  Big Cities   FC   4  5.0  4.0  4.0   1   
14    14  12/29/2011           Bursa       Other   FC   2  2.0  4.0  4.0   1   
15    15  02/07/2012        İstanbul  Big Cities   IL  12  7.5  6.0  6.0   2   
16    16  01/07/2000        İstanbul  Big Cities   FC   3  5.0  4.0  4.0   2   
17    17  11/08/2009        İstanbul  Big Cities   FC   2  4.0  4.0  5.0   1   
18    18  04/21/2012           İzmir  Big Cities   IL   4  5.0  4.0  3.0   1   
19    19  08/16/2011         Sakarya       Other   IL   2  4.0  4.0  4.0   2   
20    20  08/25/2010          Elazığ       Other   IL   3  4.0  4.0  4.0   2   
21    21  01/25/2014        İstanbul  Big Cities   FC   5  5.0  4.0  4.0   2   
22    22  07/01/2006         Kayseri       Other   FC   9  6.0  6.0  6.0   4   
23    23  06/03/2009         Sakarya       Other   FC   2  4.0  4.0  4.0   2   
24    24  09/20/2009        İstanbul  Big Cities   IL   5  5.0  3.0  5.0   2   
25    25  12/23/2011       Eskişehir       Other   FC   4  4.0  5.0  5.0   2   
26    26  02/23/2010          Ankara  Big Cities   IL   3  5.0  4.0  5.0   2   
27    27  10/09/1999           Bursa       Other   FC   4  5.0  4.0  3.0   1   
28    28  01/28/1998        İstanbul  Big Cities   IL   4  5.0  4.0  4.0   1   
29    29  10/13/2006          Ankara  Big Cities   FC   1  1.0  4.0  4.0   2   
..   ...         ...             ...         ...  ...  ..  ...  ...  ...  ..   
107  107  05/01/2011          Samsun       Other   IL   4  4.0  4.0  4.0   1   
108  108  07/09/2012           Muğla       Other   FC   1  2.0  5.0  4.0   1   
109  109  08/25/2007          Ankara  Big Cities   FC   2  4.0  3.0  5.0   4   
110  110  09/26/2012          Amasya       Other   IL   6  3.0  6.0  6.0   4   
111  111  08/10/2012         Kütahya       Other   FC   2  3.0  4.0  4.0   2   
112  112  03/14/1998        İstanbul  Big Cities   IL   4  5.0  5.0  4.0   1   
113  113  12/09/2006        Tekirdağ       Other   FC   3  4.0  4.0  4.0   1   
114  114  12/06/2008       Eskişehir       Other   IL   4  5.0  5.0  4.0   2   
115  115  05/04/2012        İstanbul  Big Cities   IL   6  4.5  6.0  6.0   4   
116  116  03/30/2012           İzmir  Big Cities   FC   2  4.0  4.0  4.0   2   
117  117  12/27/2005          Ankara  Big Cities   IL   3  5.0  4.0  5.0   3   
118  118  12/25/2009        İstanbul  Big Cities   IL  12  7.5  7.5  4.5   2   
119  119  01/03/2014        İstanbul  Big Cities   IL   4  5.0  4.0  4.0   2   
120  120  08/18/2011           Aydın       Other   FC   2  3.0  4.0  4.0   2   
121  121  11/13/2004           İzmir  Big Cities   FC   2  4.0  4.0  4.0   2   
122  122  04/10/1997        İstanbul  Big Cities   IL  12  7.5  6.0  7.5   2   
123  123  11/05/2011            Bolu       Other   FC   1  1.0  4.0  3.0   1   
124  124  08/18/2005          Ankara  Big Cities   DT   1  3.0  0.0  5.0   5   
125  1

In [14]:
end_dt = datetime.datetime.strptime('2015-1-1', "%Y-%m-%d")
train['Age'] = [(end_dt - datetime.datetime.strptime(open_dt, "%m/%d/%Y")).days for open_dt in train['Open Date']]

In [15]:
X = train['Age'].values
X = np.expand_dims(X,1)

In [16]:
y = train['revenue'].values

In [17]:
X

array([[5647],
       [2513],
       [ 663],
       [1064],
       [2063],
       [1784],
       [1543],
       [1290],
       [1587],
       [1142],
       [ 510],
       [ 954],
       [ 672],
       [1538],
       [1099],
       [1059],
       [5473],
       [1880],
       [ 985],
       [1234],
       [1590],
       [ 341],
       [3106],
       [2038],
       [1929],
       [1105],
       [1773],
       [5563],
       [6182],
       [3002],
       [2222],
       [ 731],
       [2175],
       [ 618],
       [1016],
       [6812],
       [2428],
       [1592],
       [1444],
       [2105],
       [1422],
       [2040],
       [1192],
       [1925],
       [3732],
       [1064],
       [1225],
       [1835],
       [1107],
       [2466],
       [1706],
       [1150],
       [ 415],
       [ 643],
       [5689],
       [2333],
       [ 656],
       [2385],
       [ 995],
       [2588],
       [ 975],
       [2407],
       [1508],
       [ 514],
       [6016],
       [ 376],
       [18

In [18]:
y

array([  5653753.,   6923131.,   2055379.,   2675511.,   4316715.,
         5017319.,   5166635.,   4491607.,   4952497.,   5444227.,
         3745135.,   5161370.,   1734634.,   4807746.,   1999097.,
         3218918.,  19696939.,   8213524.,   5337526.,   2021934.,
         5525735.,   1149870.,   3956086.,   2999068.,   8904084.,
         3778621.,   2267425.,   5435276.,   4705945.,   3447890.,
         3008199.,   2058644.,   3261924.,   2371202.,   4100886.,
         3903884.,   3028267.,   2740687.,   5461700.,   3818055.,
         6836483.,   4554237.,   4952255.,   2732645.,   4264176.,
         3752885.,   4250758.,   7865428.,   7201784.,   8630682.,
         2156098.,   3273041.,   1763231.,   5595267.,   4651866.,
         6941173.,   2390534.,   3258837.,   3004429.,   3600467.,
         3164972.,   4350573.,   5286212.,   1619683.,   2551252.,
         1756069.,   1882131.,   4052733.,   3836721.,   3452382.,
         3982767.,   4136425.,   2525375.,   3347767.,   55008

In [19]:
loo = sklearn.cross_validation.LeaveOneOut(len(y))

In [20]:
for train_index, test_index in loo:
    print("TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(X_test, y_test)

TEST: [0]
[[5647]] [ 5653753.]
TEST: [1]
[[2513]] [ 6923131.]
TEST: [2]
[[663]] [ 2055379.]
TEST: [3]
[[1064]] [ 2675511.]
TEST: [4]
[[2063]] [ 4316715.]
TEST: [5]
[[1784]] [ 5017319.]
TEST: [6]
[[1543]] [ 5166635.]
TEST: [7]
[[1290]] [ 4491607.]
TEST: [8]
[[1587]] [ 4952497.]
TEST: [9]
[[1142]] [ 5444227.]
TEST: [10]
[[510]] [ 3745135.]
TEST: [11]
[[954]] [ 5161370.]
TEST: [12]
[[672]] [ 1734634.]
TEST: [13]
[[1538]] [ 4807746.]
TEST: [14]
[[1099]] [ 1999097.]
TEST: [15]
[[1059]] [ 3218918.]
TEST: [16]
[[5473]] [ 19696939.]
TEST: [17]
[[1880]] [ 8213524.]
TEST: [18]
[[985]] [ 5337526.]
TEST: [19]
[[1234]] [ 2021934.]
TEST: [20]
[[1590]] [ 5525735.]
TEST: [21]
[[341]] [ 1149870.]
TEST: [22]
[[3106]] [ 3956086.]
TEST: [23]
[[2038]] [ 2999068.]
TEST: [24]
[[1929]] [ 8904084.]
TEST: [25]
[[1105]] [ 3778621.]
TEST: [26]
[[1773]] [ 2267425.]
TEST: [27]
[[5563]] [ 5435276.]
TEST: [28]
[[6182]] [ 4705945.]
TEST: [29]
[[3002]] [ 3447890.]
TEST: [30]
[[2222]] [ 3008199.]
TEST: [31]
[[731]] [ 20

In [21]:
cv = StratifiedPercentileKFold.StratifiedPercentileKFold(y, n_folds=10, random_state=0)
for train_index, test_index in cv:
    print("TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(X_test)
    print(y_test)

TEST: [  7  21  25  42  47  74  90  96 102 109 117 129 131]
[[1290]
 [ 341]
 [1105]
 [1192]
 [1835]
 [1127]
 [ 511]
 [1131]
 [3764]
 [2686]
 [3292]
 [2884]
 [4439]]
[ 4491607.  1149870.  3778621.  4952255.  7865428.  5500818.  3426169.
  6412623.  2738052.  4219263.  2018785.  3939804.  3199619.]
TEST: [  8  15  17  19  20  22  37  41  84  89  95  97 121]
[[1587]
 [1059]
 [1880]
 [1234]
 [1590]
 [3106]
 [1592]
 [2040]
 [1910]
 [2061]
 [ 937]
 [2166]
 [3701]]
[ 4952497.  3218918.  8213524.  2021934.  5525735.  3956086.  2740687.
  4554237.  4250553.  2364478.  1270499.  6694797.  3445076.]
TEST: [  5  29  33  46  49  63  70  76  88  92 105 107 119]
[[1784]
 [3002]
 [ 618]
 [1225]
 [2466]
 [ 514]
 [2957]
 [2228]
 [ 540]
 [4444]
 [2483]
 [1341]
 [ 363]]
[ 5017319.  3447890.  2371202.  4250758.  8630682.  1619683.  3982767.
  4590423.  2025297.  6782425.  2792031.  3248660.  3780019.]
TEST: [  2  11  12  40  53  54  57  69 110 112 116 123 126 128]
[[ 663]
 [ 954]
 [ 672]
 [1422]
 [ 643]
 [

In [22]:
clf = sklearn.linear_model.LinearRegression()

In [23]:
clf

LinearRegression(copy_X=True, fit_intercept=True, normalize=False)

In [24]:
cv = sklearn.cross_validation.KFold(len(y), n_folds=10, random_state=0)
scores = []
for train_index, test_index in cv:
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    # Compute mean squared error
    mse = sklearn.metrics.mean_squared_error(y_test,y_pred)
    print(mse**0.5)
    scores.append(mse)

# Average RMSE from cross validation
scores = np.array(scores)
print("CV Score: {}".format(np.mean(scores)**0.5))
print("CV Score stdev: {}".format(np.std(scores**0.5)))
print("CV Score error: {}".format(np.std(scores**0.5) / np.mean(scores)**0.5))

1215755.89952
4292859.49464
1836846.89118
2185794.46848
1718161.88985
3250265.56515
1618143.80711
2725122.1065
2582430.08249
2165261.49388
CV Score: 2509515.8472386408
CV Score stdev: 855853.9769881696
CV Score error: 0.34104346379398764


In [25]:
cv = StratifiedPercentileKFold.StratifiedPercentileKFold(y, n_folds=10, random_state=0)
scores = []
for train_index, test_index in cv:
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    # Compute mean squared error
    mse = sklearn.metrics.mean_squared_error(y_test,y_pred)
    print(mse**0.5)
    scores.append(mse)

# Average RMSE from cross validation
scores = np.array(scores)
print("CV Score Mean: {}".format(np.mean(scores)**0.5))
print("CV Score stdev: {}".format(np.std(scores**0.5)))
print("CV Score error: {}".format(np.std(scores**0.5) / np.mean(scores)**0.5))

2061943.30157
1844942.24135
1594973.86056
2199623.47419
1748903.59447
2014918.85682
2091279.46355
2583351.14305
3319821.9414
3997010.49684
CV Score Mean: 2453583.7551755453
CV Score stdev: 719634.2253128553
CV Score error: 0.2932992296655339


In [26]:
loo = sklearn.cross_validation.LeaveOneOut(len(y))
scores = []
for train_index, test_index in loo:
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    # Compute mean squared error
    mse = sklearn.metrics.mean_squared_error(y_test,y_pred)
    print(mse**0.5)
    scores.append(mse)

# Average RMSE from cross validation
scores = np.array(scores)
print("CV Score Mean: {}".format(np.mean(scores)**0.5))
print("CV Score stdev: {}".format(np.std(scores**0.5)))
print("CV Score error: {}".format(np.std(scores**0.5) / np.mean(scores)**0.5))

859668.462153
2258131.53088
1594938.07515
1193728.08732
110088.561996
756282.377681
1046074.36442
511503.097967
804676.526352
1560015.72742
208445.75576
1384449.42202
1925414.36899
687036.585013
1897402.59349
641402.187647
13963540.3126
3921259.4942
1544444.52848
1950463.82392
1380932.60668
2335655.66479
1076410.55386
1423082.25274
4588541.49222
101942.285962
2008573.48538
1036980.69143
2210469.15157
1529082.66863
1519663.96763
1629905.94418
1237016.52891
1249014.93026
275322.752479
3521402.34445
1618325.51567
1428344.88957
1401181.74051
636551.19969
2801135.49805
142401.053407
1033665.90445
1626691.70779
1132342.0734
104343.777921
305879.337216
3596686.51996
3357180.91111
4005726.08728
2082599.0989
638767.163073
1752519.75458
2008737.78109
1941314.97068
2378902.81914
1250913.73736
1361142.10081
821762.03668
1134194.45114
647903.431926
273754.64254
1186966.84586
1953819.17831
4389268.79497
1737974.35476
2422487.88709
3863.36901504
415067.024803
497668.523132
962616.547835
802222.391392

In [27]:
def do_cv(cv, clf, y_transform=None, X=X, y=y):
    if y_transform is None:
        y_transform = lambda x: x
    scores = []
    all_pred = np.zeros((y.shape))
    for train_index, test_index in cv:
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        # Fit model
        clf.fit(X_train, y_train)
        # Predict scores for test data
        y_pred = y_transform(clf.predict(X_test))
        # Save all the predictions to an array
        all_pred[test_index] = y_pred
        # Compute mean squared error on this test set
        mse = sklearn.metrics.mean_squared_error(y_transform(y_test),y_pred)
        scores.append(mse)
    # Compute MSE for 
    all_score = sklearn.metrics.mean_squared_error(y_transform(y), all_pred)**0.5
    scores = np.asarray(scores)**0.5
    return all_score, scores

In [28]:
do_cv(loo, clf)

(2488780.054547905,
 array([  8.59668462e+05,   2.25813153e+06,   1.59493808e+06,
          1.19372809e+06,   1.10088562e+05,   7.56282378e+05,
          1.04607436e+06,   5.11503098e+05,   8.04676526e+05,
          1.56001573e+06,   2.08445756e+05,   1.38444942e+06,
          1.92541437e+06,   6.87036585e+05,   1.89740259e+06,
          6.41402188e+05,   1.39635403e+07,   3.92125949e+06,
          1.54444453e+06,   1.95046382e+06,   1.38093261e+06,
          2.33565566e+06,   1.07641055e+06,   1.42308225e+06,
          4.58854149e+06,   1.01942286e+05,   2.00857349e+06,
          1.03698069e+06,   2.21046915e+06,   1.52908267e+06,
          1.51966397e+06,   1.62990594e+06,   1.23701653e+06,
          1.24901493e+06,   2.75322752e+05,   3.52140234e+06,
          1.61832552e+06,   1.42834489e+06,   1.40118174e+06,
          6.36551200e+05,   2.80113550e+06,   1.42401053e+05,
          1.03366590e+06,   1.62669171e+06,   1.13234207e+06,
          1.04343778e+05,   3.05879337e+05,   3.59

In [29]:
do_cv(loo, clf, lambda x: np.exp(x), y=np.log(y))

(2525646.8683475256,
 array([  1.07031734e+05,   2.82484532e+06,   1.34512923e+06,
          8.59285339e+05,   3.97820528e+05,   1.21914945e+06,
          1.46767929e+06,   8.88989995e+05,   1.23442327e+06,
          1.90675938e+06,   4.30555112e+05,   1.69504871e+06,
          1.67745536e+06,   1.10855080e+06,   1.56015323e+06,
          3.06702801e+05,   1.43756206e+07,   4.38986280e+06,
          1.86058202e+06,   1.58741040e+06,   1.80982139e+06,
          2.17438817e+06,   4.33634509e+05,   9.19779239e+05,
          5.06227785e+06,   2.41674216e+05,   1.54963009e+06,
          2.82439085e+05,   1.49663380e+06,   8.98472445e+05,
          9.89112523e+05,   1.36583525e+06,   7.12777483e+05,
          1.00620126e+06,   6.01303127e+05,   2.92301741e+06,
          1.05899828e+06,   9.97689857e+05,   1.80439789e+06,
          1.22184938e+05,   3.19536925e+06,   6.46595963e+05,
          1.39164878e+06,   1.14153446e+06,   4.31901862e+05,
          2.31397607e+05,   6.71684791e+05,   4.0

In [30]:
scaler = boxcoxscaler.BoxCoxScaler(standardise=True)

scaler.fit(np.log(np.expand_dims(y,1)))
y_transform_fn = lambda x: np.exp(scaler.inverse_transform(x))

In [31]:
scaler.transform(np.log(np.expand_dims(y,1)))

array([[ 0.77501775],
       [ 1.16780643],
       [-1.40605015],
       [-0.79981012],
       [ 0.23039875],
       [ 0.53705764],
       [ 0.59593916],
       [ 0.31214629],
       [ 0.51085385],
       [ 0.70029125],
       [-0.06658081],
       [ 0.59389698],
       [-1.81166128],
       [ 0.45086148],
       [-1.47157415],
       [-0.39133469],
       [ 3.00031543],
       [ 1.48906916],
       [ 0.66093274],
       [-1.4447276 ],
       [ 0.729754  ],
       [-2.84873441],
       [ 0.04885786],
       [-0.54604396],
       [ 1.63768287],
       [-0.04775393],
       [-1.17695311],
       [ 0.69702432],
       [ 0.40738881],
       [-0.24288401],
       [-0.53935615],
       [-1.4023142 ],
       [-0.36252384],
       [-1.0738658 ],
       [ 0.12399468],
       [ 0.02097548],
       [-0.5247413 ],
       [-0.74588197],
       [ 0.70665047],
       [-0.02583236],
       [ 1.14376928],
       [ 0.34051788],
       [ 0.51075527],
       [-0.75245401],
       [ 0.20508045],
       [-0

In [32]:
do_cv(loo, clf, y_transform_fn, y=scaler.transform(np.log(np.expand_dims(y,1))))

(2539389.3037002329,
 array([    33512.65780534,   2906258.49066114,   1292706.537078  ,
           798781.16946591,    474449.91493522,   1291390.12454626,
          1535956.85074639,    953228.02099925,   1303527.54100992,
          1967808.440365  ,    480484.7693422 ,   1752734.81669257,
          1625624.5995547 ,   1176904.12313181,   1499669.9409668 ,
           246199.4735318 ,  14416371.28290601,   4462094.98363888,
          1918741.6753341 ,   1524488.86934971,   1878713.56242062,
          2132905.45698259,    345225.40107321,    843419.23615319,
          5134924.98914211,    302895.16599223,   1477553.79280748,
           206818.07519105,   1440999.21189223,    810944.7068221 ,
           910234.67398944,   1312098.45992335,    634482.16978558,
           954219.60416589,    660773.77644453,   2908490.58876728,
           977510.48104257,    928153.47802425,   1870848.07236536,
            44864.63715135,   3260674.29887588,    722830.22060983,
          1453904.5846573 ,

In [33]:
boxcoxscaler.BoxCoxScaler().fit_transform(X)

/usr/local/lib/python3.4/dist-packages/sklearn/utils/validation.py:332: UserWarning: BoxCoxScaler assumes floating point values as input, got int64
  "got %s" % (estimator, X.dtype))


array([[ 1.82431342],
       [ 0.57973475],
       [-1.39676307],
       [-0.70514548],
       [ 0.28147999],
       [ 0.06309655],
       [-0.15397243],
       [-0.420387  ],
       [-0.11200023],
       [-0.60076426],
       [-1.77570167],
       [-0.86567413],
       [-1.37719908],
       [-0.158815  ],
       [-0.65742292],
       [-0.71208656],
       [ 1.77557656],
       [ 0.14174985],
       [-0.81869418],
       [-0.48616448],
       [-0.1091796 ],
       [-2.35067728],
       [ 0.90216283],
       [ 0.26311489],
       [ 0.18041114],
       [-0.64938972],
       [ 0.05382424],
       [ 1.8009693 ],
       [ 1.96555472],
       [ 0.85017766],
       [ 0.39347772],
       [-1.25489329],
       [ 0.36119992],
       [-1.49860471],
       [-0.77312232],
       [ 2.11745397],
       [ 0.52758161],
       [-0.10730204],
       [-0.25280505],
       [ 0.31185442],
       [-0.27565604],
       [ 0.26459209],
       [-0.53741959],
       [ 0.17729091],
       [ 1.18344514],
       [-0

In [34]:
do_cv(loo, clf, y_transform_fn, X=boxcoxscaler.BoxCoxScaler().fit_transform(X), y=scaler.transform(np.log(np.expand_dims(y,1))))

/usr/local/lib/python3.4/dist-packages/sklearn/utils/validation.py:332: UserWarning: BoxCoxScaler assumes floating point values as input, got int64
  "got %s" % (estimator, X.dtype))


(2488845.1161016398,
 array([  9.95526313e+04,   2.61496202e+06,   9.39800035e+05,
          7.12194919e+05,   2.36588887e+05,   1.11180238e+06,
          1.42312725e+06,   9.32574066e+05,   1.17724064e+06,
          2.01333944e+06,   9.99382786e+05,   1.90146299e+06,
          1.28314286e+06,   1.06582135e+06,   1.43049035e+06,
          1.57240973e+05,   1.43886322e+07,   4.26124370e+06,
          2.04883094e+06,   1.51852909e+06,   1.75132166e+06,
          1.45490547e+06,   6.65945190e+05,   1.07831540e+06,
          4.92424490e+06,   3.67686592e+05,   1.65458037e+06,
          9.85581603e+04,   1.05731595e+06,   1.13384774e+06,
          1.17588761e+06,   1.01425894e+06,   8.92428910e+05,
          5.58767704e+05,   7.73029104e+05,   2.10662970e+06,
          1.26940421e+06,   1.05476996e+06,   1.79078496e+06,
          2.90537296e+05,   3.18776321e+06,   4.89284453e+05,
          1.47586943e+06,   1.27939583e+06,   6.26844708e+05,
          3.77968875e+05,   7.42323419e+05,   3.9

In [35]:
do_cv(loo, clf, X=boxcoxscaler.BoxCoxScaler().fit_transform(X))

/usr/local/lib/python3.4/dist-packages/sklearn/utils/validation.py:332: UserWarning: BoxCoxScaler assumes floating point values as input, got int64
  "got %s" % (estimator, X.dtype))


(2444451.7570994738,
 array([   485121.35993921,   1957992.04631665,   1144171.84471844,
          1145029.94488104,    397622.76465698,    509762.15519722,
           860481.85013626,    426569.59380202,    605970.4322037 ,
          1556104.79472252,    945789.21611022,   1519699.57367405,
          1489678.15720859,    503362.90682674,   1872188.48354647,
           589237.15947804,  14043690.39304679,   3657463.76525686,
          1653603.85512561,   2004644.09846632,   1180869.97583787,
          1209409.55420633,   1341061.7047925 ,   1708661.05197309,
          4317942.82398473,     81289.87695854,   2251864.06483299,
           688219.82627612,   1603833.66391443,   1806632.2854365 ,
          1820880.4706063 ,   1270000.50163488,   1534924.32309704,
           727716.7582074 ,    359276.12466424,   2591749.83114265,
          1926198.46133402,   1626628.92938564,   1249292.28440182,
           928391.48008739,   2656153.05688848,    142622.83089009,
          1000096.18478174,

In [36]:
do_cv(loo, clf, y_transform_fn, X=boxcoxscaler.BoxCoxScaler().fit_transform(X), y=scaler.transform(np.log(np.expand_dims(y,1))))

/usr/local/lib/python3.4/dist-packages/sklearn/utils/validation.py:332: UserWarning: BoxCoxScaler assumes floating point values as input, got int64
  "got %s" % (estimator, X.dtype))


(2488845.1161016398,
 array([  9.95526313e+04,   2.61496202e+06,   9.39800035e+05,
          7.12194919e+05,   2.36588887e+05,   1.11180238e+06,
          1.42312725e+06,   9.32574066e+05,   1.17724064e+06,
          2.01333944e+06,   9.99382786e+05,   1.90146299e+06,
          1.28314286e+06,   1.06582135e+06,   1.43049035e+06,
          1.57240973e+05,   1.43886322e+07,   4.26124370e+06,
          2.04883094e+06,   1.51852909e+06,   1.75132166e+06,
          1.45490547e+06,   6.65945190e+05,   1.07831540e+06,
          4.92424490e+06,   3.67686592e+05,   1.65458037e+06,
          9.85581603e+04,   1.05731595e+06,   1.13384774e+06,
          1.17588761e+06,   1.01425894e+06,   8.92428910e+05,
          5.58767704e+05,   7.73029104e+05,   2.10662970e+06,
          1.26940421e+06,   1.05476996e+06,   1.79078496e+06,
          2.90537296e+05,   3.18776321e+06,   4.89284453e+05,
          1.47586943e+06,   1.27939583e+06,   6.26844708e+05,
          3.77968875e+05,   7.42323419e+05,   3.9

In [37]:
from collections import defaultdict

In [38]:
import time

In [39]:
all_score = defaultdict(lambda: defaultdict(list))
all_time  = defaultdict(dict)

In [40]:
all_score

defaultdict(<function <lambda> at 0x7f45eb1b2bf8>, {})

In [41]:
imp.reload(StratifiedPercentileKFold)

<module 'eat_it.StratifiedPercentileKFold' from '/home/scott/Documents/git/bite-me/eat_it/StratifiedPercentileKFold.py'>

In [42]:
# Box-Cox X and y
for n_folds in [3, 5, 10, 12, 15, 20]:
    t0 = time.time()
    for seed in range(100):
        cv = StratifiedPercentileKFold.StratifiedPercentileKFold(y, n_folds=n_folds, shuffle=True, random_state=seed)
        this_score, _ = do_cv(cv, clf, y_transform_fn, X=boxcoxscaler.BoxCoxScaler().fit_transform(X), y=scaler.transform(np.log(np.expand_dims(y,1))))
        all_score['Stratified'][n_folds].append(this_score)
    all_time['Stratified'][n_folds] = time.time()-t0

/usr/local/lib/python3.4/dist-packages/sklearn/utils/validation.py:332: UserWarning: BoxCoxScaler assumes floating point values as input, got int64
  "got %s" % (estimator, X.dtype))


In [43]:
# Box-Cox X and y
for n_folds in [3, 5, 10, 12, 15, 20]:
    t0 = time.time()
    for seed in range(100):
        cv = sklearn.cross_validation.KFold(len(y), n_folds=n_folds, shuffle=True, random_state=seed)
        this_score, _ = do_cv(cv, clf, y_transform_fn, X=boxcoxscaler.BoxCoxScaler().fit_transform(X), y=scaler.transform(np.log(np.expand_dims(y,1))))
        all_score['KFold'][n_folds].append(this_score)
    all_time['KFold'][n_folds] = time.time()-t0

/usr/local/lib/python3.4/dist-packages/sklearn/utils/validation.py:332: UserWarning: BoxCoxScaler assumes floating point values as input, got int64
  "got %s" % (estimator, X.dtype))


In [44]:
# Box-Cox X and y
cv = sklearn.cross_validation.LeaveOneOut(len(y))
t0 = time.time()
this_score, _ = do_cv(cv, clf, y_transform_fn, X=boxcoxscaler.BoxCoxScaler().fit_transform(X), y=scaler.transform(np.log(np.expand_dims(y,1))))
all_score['LOO'][0] = np.array(this_score)
all_time['LOO'][0] = time.time()-t0

/usr/local/lib/python3.4/dist-packages/sklearn/utils/validation.py:332: UserWarning: BoxCoxScaler assumes floating point values as input, got int64
  "got %s" % (estimator, X.dtype))


In [45]:
all_time

defaultdict(<class 'dict'>, {'Stratified': {3: 0.346388578414917, 20: 0.9988918304443359, 5: 0.4161853790283203, 10: 0.6221387386322021, 12: 0.689866304397583, 15: 0.8117880821228027}, 'LOO': {0: 0.06087660789489746}, 'KFold': {3: 0.3387308120727539, 20: 1.0288934707641602, 5: 0.415968656539917, 10: 0.6195757389068604, 12: 0.6980161666870117, 15: 0.8169872760772705}})

In [67]:
for cvtype in all_score.keys():
    for n_folds in sorted(all_score[cvtype].keys()):
        mu = np.mean(all_score[cvtype][n_folds])
        st = np.std(all_score[cvtype][n_folds])
        if isinstance(all_score[cvtype][n_folds], int):
            se = st
        elif isinstance(all_score[cvtype][n_folds], np.ndarray) and all_score[cvtype][n_folds].size==1:
            se = st
        else:
            se = st/(len(all_score[cvtype][n_folds])**0.5)
        print("{:12}{}\t{}\t{}\t{}\t{}".format(cvtype, n_folds, mu, st, se, se/mu))

Stratified  3	2467692.5606631087	8762.295555288734	876.2295555288734	0.0003550805191443364
Stratified  5	2471346.754868282	7305.1808961420265	730.5180896142026	0.0002955951398463862
Stratified  10	2475107.7166800853	7424.602388801629	742.4602388801629	0.0002999708796011677
Stratified  12	2476743.1307072327	5795.54427876533	579.554427876533	0.00023399860110282877
Stratified  15	2478250.083568183	5136.400338746504	513.6400338746504	0.0002072591613252815
Stratified  20	2477552.7041083975	5336.634115056799	533.6634115056798	0.00021539941839410052
LOO         0	2488845.11610164	0.0	0.0	0.0
KFold       3	2493359.3026256603	30576.154954264763	3057.615495426476	0.0012263036026162052
KFold       5	2491639.000301601	18192.718893936642	1819.2718893936642	0.0007301506715753968
KFold       10	2490452.4275026536	10658.977355844347	1065.8977355844347	0.00042799361425798567
KFold       12	2490636.819347439	10625.359619391267	1062.5359619391268	0.0004266121634777395
KFold       15	2489677.2352261185	95

In [59]:
isinstance(all_score[cvtype][n_folds], int)

False

In [64]:
all_score[cvtype][n_folds].size

1

In [47]:
all_score['Stratified'][5]

[2464977.9096372263,
 2483195.1452761316,
 2459496.2605135352,
 2459991.5746033872,
 2468197.1157372058,
 2461563.1119654169,
 2460549.7421641434,
 2466524.1277150945,
 2488038.000440395,
 2486928.0398998065,
 2468898.9433365767,
 2468191.7886594101,
 2469579.7355163605,
 2477216.2115779654,
 2462464.6300273607,
 2473742.5124316211,
 2473571.3071254902,
 2469727.8181967218,
 2466100.1030271011,
 2474491.2358585903,
 2470040.5775428545,
 2467132.8123095292,
 2468765.2961080465,
 2468197.9132362683,
 2473938.773705469,
 2472193.1886981418,
 2464588.1813804694,
 2475762.9871486053,
 2476009.1943099247,
 2461077.2100127414,
 2475143.4140860368,
 2482620.1999151437,
 2461486.5628721132,
 2482490.3163366779,
 2456961.3870343249,
 2460670.6166521003,
 2479991.6121238135,
 2459536.4702781891,
 2479009.2955639646,
 2472500.1070907353,
 2480208.7237387281,
 2472246.4881631387,
 2464621.7400837867,
 2470286.5996070914,
 2465530.2812307137,
 2475868.3861060822,
 2481490.4133176515,
 2470801.063352

In [48]:
np.sqrt(137)

11.704699910719626

In [49]:
all_score2 = defaultdict(lambda: defaultdict(list))
all_time2  = defaultdict(dict)

In [50]:
# Box-Cox transform X, but NOT y
for n_folds in [3, 5, 10, 12, 15, 20]:
    t0 = time.time()
    for seed in range(100):
        cv = StratifiedPercentileKFold.StratifiedPercentileKFold(y, n_folds=n_folds, shuffle=True, random_state=seed)
        this_score, _ = do_cv(cv, clf, X=boxcoxscaler.BoxCoxScaler().fit_transform(X))
        all_score2['Stratified'][n_folds].append(this_score)
    all_time2['Stratified'][n_folds] = time.time()-t0

/usr/local/lib/python3.4/dist-packages/sklearn/utils/validation.py:332: UserWarning: BoxCoxScaler assumes floating point values as input, got int64
  "got %s" % (estimator, X.dtype))


In [51]:
for cvtype in all_score2.keys():
    for n_folds in sorted(all_score2[cvtype].keys()):
        mu = np.mean(all_score2[cvtype][n_folds])
        st = np.std(all_score2[cvtype][n_folds])
        print("{:12}{}\t{}\t{}\t{}\t".format(cvtype, n_folds, mu, st, st/mu))

Stratified  3	2412427.178429039	11887.005835357722	0.004927405039060488	
Stratified  5	2419095.592848078	9439.349988275711	0.0039020161155196294	
Stratified  10	2426179.716817545	8987.946290316757	0.0037045674020003663	
Stratified  12	2429239.328273662	6972.638940202916	0.0028702972403950085	
Stratified  15	2430937.203985103	6510.8343843501125	0.0026783227364642415	
Stratified  20	2430261.753168016	5581.228759375891	0.0022965545798103305	


In [53]:
all_score2 = defaultdict(lambda: defaultdict(list))
all_time2  = defaultdict(dict)

In [54]:
# Shuffle windows
for n_folds in [3, 5, 10, 12, 15, 20]:
    t0 = time.time()
    for seed in range(100):
        cv = StratifiedPercentileKFold.StratifiedPercentileKFold(y, n_folds=n_folds, shuffle=True, random_state=seed, shuffle_windows=True)
        this_score, _ = do_cv(cv, clf, y_transform_fn, X=boxcoxscaler.BoxCoxScaler().fit_transform(X), y=scaler.transform(np.log(np.expand_dims(y,1))))
        all_score2['Stratified'][n_folds].append(this_score)
    all_time2['Stratified'][n_folds] = time.time()-t0

/usr/local/lib/python3.4/dist-packages/sklearn/utils/validation.py:332: UserWarning: BoxCoxScaler assumes floating point values as input, got int64
  "got %s" % (estimator, X.dtype))


In [55]:
for cvtype in all_score2.keys():
    for n_folds in sorted(all_score2[cvtype].keys()):
        mu = np.mean(all_score2[cvtype][n_folds])
        st = np.std(all_score2[cvtype][n_folds])
        print("{:12}{}\t{}\t{}\t{}\t".format(cvtype, n_folds, mu, st, st/mu))

Stratified  3	2468427.403577588	8992.595189359801	0.0036430462473097175	
Stratified  5	2473199.4401780698	9933.849093394056	0.004016598472413863	
Stratified  10	2475330.175770797	6909.008298429096	0.002791146153372323	
Stratified  12	2475574.92905556	6639.379902601878	0.00268195473490872	
Stratified  15	2477408.8472560137	6392.236590544554	0.002580210609009739	
Stratified  20	2476903.9775353037	4802.419516407234	0.0019388799727254606	


In [68]:
# Reminder: this is what the original data looked like
for cvtype in all_score.keys():
    for n_folds in sorted(all_score[cvtype].keys()):
        mu = np.mean(all_score[cvtype][n_folds])
        st = np.std(all_score[cvtype][n_folds])
        if isinstance(all_score[cvtype][n_folds], int):
            se = st
        elif isinstance(all_score[cvtype][n_folds], np.ndarray) and all_score[cvtype][n_folds].size==1:
            se = st
        else:
            se = st/(len(all_score[cvtype][n_folds])**0.5)
        print("{:12}{}\t{}\t{}\t{}\t{}".format(cvtype, n_folds, mu, st, se, se/mu))

Stratified  3	2467692.5606631087	8762.295555288734	876.2295555288734	0.0003550805191443364
Stratified  5	2471346.754868282	7305.1808961420265	730.5180896142026	0.0002955951398463862
Stratified  10	2475107.7166800853	7424.602388801629	742.4602388801629	0.0002999708796011677
Stratified  12	2476743.1307072327	5795.54427876533	579.554427876533	0.00023399860110282877
Stratified  15	2478250.083568183	5136.400338746504	513.6400338746504	0.0002072591613252815
Stratified  20	2477552.7041083975	5336.634115056799	533.6634115056798	0.00021539941839410052
LOO         0	2488845.11610164	0.0	0.0	0.0
KFold       3	2493359.3026256603	30576.154954264763	3057.615495426476	0.0012263036026162052
KFold       5	2491639.000301601	18192.718893936642	1819.2718893936642	0.0007301506715753968
KFold       10	2490452.4275026536	10658.977355844347	1065.8977355844347	0.00042799361425798567
KFold       12	2490636.819347439	10625.359619391267	1062.5359619391268	0.0004266121634777395
KFold       15	2489677.2352261185	95

In [49]:
all_score2 = defaultdict(lambda: defaultdict(list))
all_time2  = defaultdict(dict)

In [50]:
# Box-Cox transform X, but NOT y
for n_folds in [3, 5, 10, 12, 15, 20]:
    t0 = time.time()
    for seed in range(100):
        cv = StratifiedPercentileKFold.StratifiedPercentileKFold(y, n_folds=n_folds, shuffle=True, random_state=seed)
        this_score, _ = do_cv(cv, clf, X=boxcoxscaler.BoxCoxScaler().fit_transform(X))
        all_score2['Stratified'][n_folds].append(this_score)
    all_time2['Stratified'][n_folds] = time.time()-t0

/usr/local/lib/python3.4/dist-packages/sklearn/utils/validation.py:332: UserWarning: BoxCoxScaler assumes floating point values as input, got int64
  "got %s" % (estimator, X.dtype))


In [51]:
for cvtype in all_score2.keys():
    for n_folds in sorted(all_score2[cvtype].keys()):
        mu = np.mean(all_score2[cvtype][n_folds])
        st = np.std(all_score2[cvtype][n_folds])
        print("{:12}{}\t{}\t{}\t{}\t".format(cvtype, n_folds, mu, st, st/mu))

Stratified  3	2412427.178429039	11887.005835357722	0.004927405039060488	
Stratified  5	2419095.592848078	9439.349988275711	0.0039020161155196294	
Stratified  10	2426179.716817545	8987.946290316757	0.0037045674020003663	
Stratified  12	2429239.328273662	6972.638940202916	0.0028702972403950085	
Stratified  15	2430937.203985103	6510.8343843501125	0.0026783227364642415	
Stratified  20	2430261.753168016	5581.228759375891	0.0022965545798103305	


In [69]:
all_score2 = defaultdict(lambda: defaultdict(lambda: defaultdict(list)))
for n_folds in [3, 5, 10, 12, 15, 20]:
    for seed in range(100):
        cv = StratifiedPercentileKFold.StratifiedPercentileKFold(y, n_folds=n_folds, shuffle=True, random_state=seed)
        this_score, _ = do_cv(cv, clf)
        all_score2['X=def,y=def']['Stratified'][n_folds].append(this_score)
    for seed in range(100):
        cv = StratifiedPercentileKFold.StratifiedPercentileKFold(y, n_folds=n_folds, shuffle=True, random_state=seed)
        this_score, _ = do_cv(cv, clf, X=boxcoxscaler.BoxCoxScaler().fit_transform(X))
        all_score2['X=Box,y=def']['Stratified'][n_folds].append(this_score)
    for seed in range(100):
        cv = StratifiedPercentileKFold.StratifiedPercentileKFold(y, n_folds=n_folds, shuffle=True, random_state=seed)
        this_score, _ = do_cv(cv, clf, y_transform_fn, y=scaler.transform(np.log(np.expand_dims(y,1))))
        all_score2['X=def,y=Box']['Stratified'][n_folds].append(this_score)
    for seed in range(100):
        cv = StratifiedPercentileKFold.StratifiedPercentileKFold(y, n_folds=n_folds, shuffle=True, random_state=seed)
        this_score, _ = do_cv(cv, clf, y_transform_fn, X=boxcoxscaler.BoxCoxScaler().fit_transform(X), y=scaler.transform(np.log(np.expand_dims(y,1))))
        all_score2['X=Box,y=Box']['Stratified'][n_folds].append(this_score)
    for seed in range(100):
        cv = StratifiedPercentileKFold.StratifiedPercentileKFold(y, n_folds=n_folds, shuffle=True, random_state=seed)
        this_score, _ = do_cv(cv, clf, y_transform_fn, X=boxcoxscaler.BoxCoxScaler().fit_transform(X), y=scaler.transform(np.log(np.expand_dims(y,1))))
        all_score2['X=Box,y=Box']['Stratified'][n_folds].append(this_score)

/usr/local/lib/python3.4/dist-packages/sklearn/utils/validation.py:332: UserWarning: BoxCoxScaler assumes floating point values as input, got int64
  "got %s" % (estimator, X.dtype))


In [82]:
for n_folds in [3, 5, 10, 12, 15, 20]:
    for seed in range(100):
        cv = StratifiedPercentileKFold.StratifiedPercentileKFold(y, n_folds=n_folds, shuffle=True, random_state=seed)
        this_score, _ = do_cv(cv, clf, y_transform_fn, X=y_transform_fn(boxcoxscaler.BoxCoxScaler().fit_transform(X)), y=scaler.transform(np.log(np.expand_dims(y,1))))
        all_score2['X=yify,y=Box']['Stratified'][n_folds].append(this_score)

/usr/local/lib/python3.4/dist-packages/sklearn/utils/validation.py:332: UserWarning: BoxCoxScaler assumes floating point values as input, got int64
  "got %s" % (estimator, X.dtype))


In [83]:
for mode in all_score2.keys():
    my_score = all_score2[mode]
    for cvtype in my_score.keys():
        for n_folds in sorted(my_score[cvtype].keys()):
            mu = np.mean(my_score[cvtype][n_folds])
            st = np.std(my_score[cvtype][n_folds])
            if isinstance(my_score[cvtype][n_folds], int):
                se = st
            elif isinstance(my_score[cvtype][n_folds], np.ndarray) and all_score[cvtype][n_folds].size==1:
                se = st
            else:
                se = st/(len(my_score[cvtype][n_folds])**0.5)
            print("{}\t{:12}{}\t{}\t{}\t{}".format(mode, cvtype, n_folds, mu, se, se/mu))

X=def,y=Box	Stratified  3	2516211.0209872904	2265.8313179479383	0.0009004933604729582
X=def,y=Box	Stratified  5	2521535.1312306914	1471.7336212178036	0.0005836657213256796
X=def,y=Box	Stratified  10	2526200.2287378507	1179.7542794542928	0.00046700743117410214
X=def,y=Box	Stratified  12	2528497.826242829	935.0315246058071	0.00036979724281400653
X=def,y=Box	Stratified  15	2529397.286305249	846.3960270173726	0.00033462360049169005
X=def,y=Box	Stratified  20	2527774.913379252	792.5237739911984	0.0003135262438900124
X=Box,y=def	Stratified  3	2412427.178429039	1188.7005835357722	0.0004927405039060488
X=Box,y=def	Stratified  5	2419095.592848078	943.9349988275711	0.0003902016115519629
X=Box,y=def	Stratified  10	2426179.716817545	898.7946290316756	0.00037045674020003665
X=Box,y=def	Stratified  12	2429239.328273662	697.2638940202917	0.0002870297240395009
X=Box,y=def	Stratified  15	2430937.203985103	651.0834384350112	0.0002678322736464241
X=Box,y=def	Stratified  20	2430261.753168016	558.122875937

In [106]:
n_samp = 25
overall = all_score2['X=Box,y=def']['Stratified'][5]
samp = overall[0:n_samp]
mu = np.mean(overall)
se = np.std(overall)/(len(overall)**0.5)
print('{}\t{}\t{}'.format(mu,se,se/mu))
mu = np.mean(samp)
se = np.std(samp)/(len(samp)**0.5)
print('{}\t{}\t{}'.format(mu,se,se/mu))

2419095.592848078	943.9349988275711	0.0003902016115519629
2418330.8583189095	2004.5818133821188	0.0008289113156235345
